name: Install SystemC on macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install cmake
          echo "CXX=clang++" >> $GITHUB_ENV

      - name: Verify architecture
        run: |
          if [[ "$(uname -m)" != "arm64" ]]; then
            echo "Error: Not running on Apple Silicon (ARM64)." >&2
            exit 1
          fi
          echo "Running on Apple Silicon (ARM64)."

      - name: Download and extract SystemC
        run: |
          curl -LO https://github.com/accellera-official/systemc/archive/refs/tags/2.3.4.tar.gz
          tar -xzf 2.3.4.tar.gz
          mv systemc-2.3.4 systemc-2.3.4-source

      - name: Build and install SystemC
        run: |
          mkdir -p systemc-2.3.4-source/BUILD systemc-2.3.4-source/INSTALL
          cd systemc-2.3.4-source/BUILD
          cmake -DCMAKE_CXX_STANDARD=17 -DCMAKE_CXX_STANDARD_REQUIRED=ON -DCMAKE_INSTALL_PREFIX="../INSTALL" ..
          make -j$(sysctl -n hw.ncpu)
          make install
          cd ../..

      - name: Verify installation
        run: |
          realpath systemc-2.3.4-source/INSTALL

      - name: Run SystemC test
        run: |
          echo '#include <systemc.h>' > test.cpp
          echo 'int sc_main(int argc, char* argv[]) {' >> test.cpp
          echo '  std::cout << "SystemC is working!" << std::endl;' >> test.cpp
          echo '  return 0;' >> test.cpp
          echo '}' >> test.cpp
          g++ -std=c++17 -I systemc-2.3.4-source/INSTALL/include -L systemc-2.3.4-source/INSTALL/lib -lsystemc test.cpp -o test
          ./test
